language: d
before_install:
- openssl aes-256-cbc -K $encrypted_0432792c4c40_key -iv $encrypted_0432792c4c40_iv
  -in iron.json.enc -out iron.json -d
install:
- wget -O doveralls https://github.com/ColdenCullen/doveralls/releases/download/v1.1.2/doveralls_travis
script:
- dub test -b unittest-cov
- ./doveralls
- chmod +x ./doveralls
